---

- name: Create a Virtual Machine
  hosts: guests
  user: root

  ### Can't gather facts from a machine that does not exist
  gather_facts: false

  tasks:
### Create a logical volume for storage
  - action: lvol vg=${storage} lv=lv_${inventory_hostname}_root size=10240
    delegate_to: ${host}

### Create a virtual machine
  - action: file dest=/tmp/vm-${inventory_hostname} state=directory
    delegate_to: ${host}
  - action: template src=../templates/vm.xml dest=/tmp/vm-${inventory_hostname}/vm.xml
    delegate_to: ${host}
  - action: virt_guest guest=${inventory_hostname} src=/tmp/vm-${inventory_hostname}/vm.xml
    delegate_to: ${host}
    register: guest

  - local_action: group_by key=${guest.provisioning_status}

- name: Install a minimal CentOS
  hosts: unprovisioned
  gather_facts: false
  user: root
  vars:
    kernel: ${packages_path}
  tasks:
### Prepare a kickstart file
  - action: file dest=${packages_path}/ks state=directory
    delegate_to: ${command_host}
  - action: template src=../templates/centos-6.ks dest=${packages_path}/ks/${inventory_hostname}.ks
    delegate_to: ${command_host}

  - name: Copy kernel and initrd to host
    action: get_url url=${packages_url}/tree/images/pxeboot/$item dest=/tmp/vm-${inventory_hostname}/$item
    with_items:
    - vmlinuz
    - initrd.img
    delegate_to: ${host}

### Boot the VM using the ISO image
  - action: virt_boot guest=${inventory_hostname} kernel=/tmp/vm-${inventory_hostname}/vmlinuz initrd=/tmp/vm-${inventory_hostname}/initrd.img cmdline="linux sshd ksdevice=eth0 ip=${ip} netmask=255.255.255.0 gateway=192.168.122.1 ks=${packages_url}/ks/${inventory_hostname}.ks"
    delegate_to: ${host}

### Wait for kickstart to finish
  - action: wait_for host=${ip} port=22 state=started
    delegate_to: ${command_host}

  - action: wait_for host=${ip} port=22 state=stopped timeout=3600
    delegate_to: ${command_host}

  - local_action: pause seconds=60

- name: Start the Virtual Machines
  hosts: guests
  user: root

  ### Can't gather facts from a machine that does not exist
  gather_facts: false

  tasks:
  - action: virt_boot guest=${inventory_hostname} boot=hd
    delegate_to: ${host}
    tags:
    - post_install

  - action: wait_for host=${ip} port=22 state=started
    delegate_to: ${command_host}
    tags:
    - post_install

  - action: lineinfile dest=/etc/hosts regexp=" ${inventory_hostname}$" line="${ip} ${inventory_hostname}"
    delegate_to: ${command_host}
    tags:
    - post_install

  - name: Configure yum on the newly provisioned machine
    action: template src=../templates/etc/yum.repos.d/ws.repo dest=/etc/yum.repos.d/ws.repo
    tags:
    - post_install

  - name: Remove default CentOS repos
    action: file dest=/etc/yum.repos.d/$item state=absent
    with_items:
    - CentOS-Base.repo
    - CentOS-Debuginfo.repo
    - CentOS-Media.repo
    - CentOS-Vault.repo
    - epel.repo
    - epel-testing.repo
    tags:
    - post_install
